const $=id=>document.getElementById(id);
let endpoint='',token='',role='',data={items:[],sources:[]},visit='',active=null,recommendation=null,savedText='',busy=false;
const storage={get(key){try{return localStorage.getItem(key);}catch{return null;}},set(key,value){try{localStorage.setItem(key,value);}catch{}}};
$('endpoint').value=storage.get('monitorEndpoint')||storage.get('dashboard_ai_endpoint')||'https://sampson-cay-dashboard-ai.john-aymes.workers.dev';
const esc=text=>String(text??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const date=text=>text?new Date(text).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Nassau'}):'Not available';
const safeLink=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:'#';}catch{return '#';}};
const message=(text,error=false)=>{$('message').textContent=text;$('message').classList.toggle('error',error);};
async function api(path,method='GET',body) {
  const r=await fetch(endpoint+path,{method,headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
  const value=await r.json();if(!r.ok)throw Error(value.error||'Request failed');return value;
}
function visitKey(){return `monitorVisit:${endpoint}`;}
async function load(){const first=await api('/feed'),items=[...first.items];let cursor=first.nextCursor;while(cursor){const page=await api('/feed?cursor='+encodeURIComponent(JSON.stringify(cursor)));items.push(...page.items);cursor=page.nextCursor;}data={...first,items:[...new Map(items.map(item=>[item.id,item])).values()]};role=data.role;$('mode').textContent=role==='editor'?'Private editor access':'Client view';$('coverage').textContent=data.coverage;render();}
$('connect').onsubmit=async e=>{e.preventDefault();try{const u=new URL($('endpoint').value);if(u.protocol!=='https:' && !['localhost','127.0.0.1'].includes(u.hostname))throw Error('Use an HTTPS service URL');endpoint=u.origin;token=$('token').value.trim();if(!token)throw Error('Enter your access token');visit=storage.get(visitKey())||new Date().toISOString();await load();storage.set('monitorEndpoint',endpoint);$('connection').hidden=true;$('refresh').disabled=false;$('seen').disabled=false;message(storage.get(visitKey())?'Feed loaded. Counts are measured from your last marked visit.':'First visit: existing items form your baseline. Mark this visit as seen when finished.');}catch(e){message(e.message,true);}};
$('refresh').onclick=async()=>{if(busy)return;busy=true;$('refresh').disabled=true;message('Checking monitored sources…');try{const r=await api('/refresh','POST');await load();message(r.busy?'A collection is running or was completed within the last five minutes. Feed reloaded.':`${r.newItems} new items · ${r.changedItems} changed pages · ${r.failures.length} collection issue(s).`);}catch(e){message(e.message,true);}finally{busy=false;$('refresh').disabled=false;}};
$('seen').onclick=()=>{visit=new Date().toISOString();storage.set(visitKey(),visit);render();message('Visit marked as seen. New counts now start from this moment.');};
for(const id of ['search','theme','view'])$(id).addEventListener('input',render);
function render(){
  const isNew=i=>i.first_seen>visit,isChanged=i=>i.first_seen<=visit&&i.changed_at>visit;
  $('new-count').textContent=data.items.filter(isNew).length;$('changed-count').textContent=data.items.filter(isChanged).length;$('review-count').textContent=data.items.filter(i=>i.review_status==='unreviewed').length;
  const healthy=data.sources.filter(s=>s.success_at&&!s.error && Date.now()-Date.parse(s.success_at)<12*3600000).length;$('health-count').textContent=`${healthy}/${data.sources.length}`;$('health-caption').textContent='Successful check within 12 hours';
  const themes=[...new Set(data.items.flatMap(i=>i.tags.map(t=>t.theme)))].sort(),selected=$('theme').value;
  $('theme').innerHTML='<option value="">All themes</option>'+themes.map(t=>`<option>${esc(t)}</option>`).join('');$('theme').value=selected;
  const query=$('search').value.toLowerCase(),view=$('view').value;
  const items=data.items.filter(i=>(!selected||i.tags.some(t=>t.theme===selected))&&`${i.title} ${i.source_id} ${i.tags.map(t=>t.theme+' '+t.matched.join(' ')).join(' ')}`.toLowerCase().includes(query)&&(view==='all'||view==='new'&&isNew(i)||view==='updated'&&isChanged(i)||view==='unreviewed'&&i.review_status==='unreviewed'||view==='counsel'&&i.review_status==='counsel'));
  $('feed').innerHTML=items.length?items.map(i=>`<article><div class="meta"><span>${esc(data.sources.find(s=>s.id===i.source_id)?.label||i.source_id)}</span>${isNew(i)?'<span class="badge">NEW THIS VISIT</span>':isChanged(i)?'<span class="badge changed">PAGE UPDATED</span>':''}<span class="badge">${esc(i.review_status==='counsel'?'FOR COUNSEL':i.review_status==='reviewed'?'REVIEWED':'AWAITING REVIEW')}</span></div><h3><a href="${esc(safeLink(i.url))}" target="_blank" rel="noopener noreferrer">${esc(i.title)}</a></h3><div class="meta">Published: ${esc(date(i.source_published_at))} · First collected: ${esc(date(i.first_seen))}</div>${i.collection_error?`<p class="notice error">Source unavailable on last check: ${esc(i.collection_error)} · ${esc(date(i.checked_at))}</p>`:''}<div class="tags">${i.tags.map(t=>`<span class="tag" title="${esc('Matched: '+t.matched.join(', ')+' · Rule '+t.ruleVersion)}">${esc(t.theme)}</span>`).join('')}</div><div class="meta">Last content change: ${esc(date(i.changed_at))}</div>${i.recommendation?`<div class="recommendation"><strong>Advisor recommendation · ${esc(date(i.recommendation_published_at))}</strong>${esc(i.recommendation)}${i.published_hash!==i.content_hash||i.collection_error?'<p class="muted">Source changed or could not be checked since this recommendation was published.</p>':''}</div>`:'<p class="muted">No published recommendation.</p>'}${role==='editor'?`<button class="secondary" data-edit="${i.id}">Review & recommend</button>`:''}</article>`).join(''):'<div class="empty"><h3>No matching coverage</h3><p>Try another filter or refresh sources. Check source health for collection gaps.</p></div>';
  $('feed').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));
  const recent=data.items.filter(i=>Date.now()-Date.parse(i.first_seen)<7*86400000),counts=themes.map(theme=>({theme,n:recent.filter(i=>i.tags.some(t=>t.theme===theme)).length})).sort((a,b)=>b.n-a.n),max=Math.max(1,...counts.map(x=>x.n));
  $('themes').innerHTML=counts.length?counts.map(x=>`<div class="theme-row"><span>${esc(x.theme)}</span><strong>${x.n}</strong><div class="bar"><i style="width:${x.n/max*100}%"></i></div></div>`).join(''):'<p class="muted">No tagged coverage collected yet.</p>';
  $('sources').innerHTML=data.sources.map(s=>`<div class="source ${s.error?'error':''}"><strong>${esc(s.label)}</strong><small>${s.error?esc(s.error):s.success_at?'Last success: '+esc(date(s.success_at)):'Not checked yet'}</small></div>`).join('');
}
async function openEditor(id){try{const r=await api('/editor/items/'+id);active=r.item;recommendation=r.recommendation;savedText=recommendation?.draft||'';$('editor-title').textContent=active.title;$('editor-source').textContent=active.url;$('source-text').textContent=active.text;$('draft').value=savedText;$('review-status').value=active.review_status;$('draft-status').textContent=recommendation?.published_at?'Published version stays visible until replaced or withdrawn.':'Draft is private. Mark the source reviewed, then save your recommendation before publishing.';$('unpublish').disabled=!recommendation?.published;$('publish').disabled=!(active.review_status==='reviewed'&&recommendation?.edited&&recommendation?.basis_hash===active.content_hash);$('editor').showModal();const c=await api(`/editor/items/${id}/captures`);$('captures').innerHTML=c.captures.map(x=>`<p><button class="secondary" data-capture="${esc(x.hash)}">Export ${esc(date(x.captured_at))}</button></p>`).join('');$('captures').querySelectorAll('[data-capture]').forEach(b=>b.onclick=async()=>{try{const value=await api(`/editor/items/${id}/captures?hash=${b.dataset.capture}`),link=document.createElement('a'),blob=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));link.href=blob;link.download=`capture-${b.dataset.capture}.json`;link.click();URL.revokeObjectURL(blob);}catch(e){$('draft-status').textContent=e.message;}});}catch(e){message(e.message,true);}}
$('draft').oninput=()=>{$('publish').disabled=true;$('draft-status').textContent='Unsaved changes. Save this edited draft before publishing.';};
$('analyse').onclick=()=>{if($('draft').value&&!confirm('Replace the current private draft with a new AI draft? The published version will stay unchanged.'))return;editAction(async()=>{$('draft-status').textContent='Generating a private draft…';const r=await api(`/editor/items/${active.id}/analyse`,'POST',{version:recommendation?.version||0,replace:!!$('draft').value});savedText=r.draft;recommendation={...recommendation,draft:r.draft,ai_text:r.draft,version:r.version,edited:0,basis_hash:active.content_hash};$('draft').value=r.draft;$('draft-status').textContent='AI draft saved privately. You must edit and save it before publishing.';});};
function closeEditor(){if($('draft').value!==savedText&&!confirm('You have unsaved recommendation changes. Leave without saving?'))return;$('editor').close();}
$('close').onclick=closeEditor;$('editor').addEventListener('cancel',e=>{e.preventDefault();closeEditor();});
async function editAction(fn){if(busy)return;busy=true;const buttons=['analyse','save','publish','unpublish','review','close'];buttons.forEach(id=>$(id).disabled=true);try{await fn();}catch(e){$('draft-status').textContent=e.message;}finally{busy=false;buttons.forEach(id=>$(id).disabled=false);$('publish').disabled=!(active.review_status==='reviewed'&&recommendation?.edited&&$('draft').value===savedText&&recommendation?.basis_hash===active.content_hash);$('unpublish').disabled=!recommendation?.published;}}
$('save').onclick=()=>editAction(async()=>{const r=await api(`/editor/items/${active.id}/draft`,'PUT',{text:$('draft').value,version:recommendation?.version||0,basisHash:active.content_hash});savedText=$('draft').value.trim();$('draft').value=savedText;recommendation={...recommendation,draft:savedText,version:r.version,edited:Number(r.edited),basis_hash:active.content_hash};$('draft-status').textContent=r.edited?(active.review_status==='reviewed'?'Edited draft saved privately. Ready for your explicit publication.':'Draft saved privately. Mark the source reviewed before publishing.'):'Draft saved. Edit the AI wording before publishing.';});
$('publish').onclick=()=>{if(!confirm('Publish this saved recommendation to the client?'))return;editAction(async()=>{const r=await api(`/editor/items/${active.id}/publish`,'POST',{version:recommendation.version});recommendation.published=savedText;$('draft-status').textContent='Recommendation published to the client at '+date(r.publishedAt);await load();});};
$('unpublish').onclick=()=>{if(!confirm('Withdraw the recommendation from the client view?'))return;editAction(async()=>{await api(`/editor/items/${active.id}/unpublish`,'POST');recommendation.published=null;$('draft-status').textContent='Published recommendation withdrawn. Your draft remains private.';await load();});};
$('review').onclick=()=>editAction(async()=>{await api(`/editor/items/${active.id}/review`,'POST',{status:$('review-status').value,basisHash:active.content_hash});active.review_status=$('review-status').value;$('draft-status').textContent='Review status saved for the current source.';await load();});
$('disconnect').onclick=()=>{token='';$('token').value='';location.reload();};
